-- VIEW DATA
SELECT *
FROM CHICAGO_CENSUS_DATA;

SELECT *
FROM CHICAGO_PUBLIC_SCHOOLS; 

SELECT * 
FROM CHICAGO_CRIME_DATA; 

-- Problem 1: Find the total number of crimes recorded in the CRIME table.
SELECT *
FROM CHICAGO_CRIME_DATA;

-- Problem 2: List community areas with per capita income less than 11000.

SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CHICAGO_CENSUS_DATA 
WHERE PER_CAPITA_INCOME < 11000;

-- Problem 3: List all case numbers for crimes involving minors?

SELECT DISTINCT CASE_NUMBER, DESCRIPTION, DATE, BLOCK, ID, PRIMARY_TYPE, LOCATION_DESCRIPTION, ARREST 
FROM CHICAGO_CRIME_DATA 
WHERE DESCRIPTION LIKE '%MINOR%';

-- Problem 4: List all kidnapping crimes involving a child?(children are not considered minors for the purposes of crime analysis)
SELECT DISTINCT CASE_NUMBER, PRIMARY_TYPE, DATE, DESCRIPTION, LOCATION_DESCRIPTION, ARREST  
FROM CHICAGO_CRIME_DATA
WHERE DESCRIPTION LIKE '%CHILD%' AND PRIMARY_TYPE LIKE '%KIDNAP%'; 

-- Problem 5: What kind of crimes were recorded at schools?
SELECT COUNT(CASE_NUMBER), PRIMARY_TYPE
FROM CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%'
GROUP BY PRIMARY_TYPE; 

-- Problem 6: List the average safety score for all types of schools.
SELECT ELEMENTARY__MIDDLE__OR_HIGH_SCHOOL, AVG(SAFETY_SCORE) AS AVG_SAFETY_SCORE
FROM CHICAGO_PUBLIC_SCHOOLS
GROUP BY ELEMENTARY__MIDDLE__OR_HIGH_SCHOOL; 

-- Problem 7: List 5 community areas with highest % of households below poverty line.
SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
FROM CHICAGO_CENSUS_DATA
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC LIMIT 5; 

-- Problem 8: Which community area(number) is most crime prone?
SELECT CEND.COMMUNITY_AREA_NUMBER, CEND.COMMUNITY_AREA_NAME, CRIME_COUNT
FROM NBD66290.CHICAGO_CENSUS_DATA AS CEND
JOIN (
    SELECT CRID.COMMUNITY_AREA_NUMBER, COUNT(CRID.ID) AS CRIME_COUNT
    FROM NBD66290.CHICAGO_CRIME_DATA AS CRID
    GROUP BY CRID.COMMUNITY_AREA_NUMBER
) AS CRIME_COUNTS ON CEND.COMMUNITY_AREA_NUMBER = CRIME_COUNTS.COMMUNITY_AREA_NUMBER
ORDER BY CRIME_COUNT DESC
LIMIT 5;
-- Problem 9: Use a sub-query to find the name of the community area with highest hardship index.
SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, HARDSHIP_INDEX
FROM CHICAGO_CENSUS_DATA 
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM CHICAGO_CENSUS_DATA);

-- Problem 10: Use a sub-query to determine the Community Area Name with most number of crimes?
SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME 
FROM CHICAGO_CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = 
		(SELECT COMMUNITY_AREA_NUMBER 
		 FROM CHICAGO_CRIME_DATA 
   		 GROUP BY COMMUNITY_AREA_NUMBER
		 ORDER BY COUNT(COMMUNITY_AREA_NUMBER) DESC
    LIMIT 1)
LIMIT 1;

